
settings:
  time:
    now: "&aСейчас открыт"

messages:
  commands:
    wrong-value: "&6&lCultPvPChests &8| &cВы ввели неверное значение {value}"
    block-is-null: "&6&lCultPvPChests &8| &cНе удалось найти блок, на который вы смотрите"
    not-exists: "&6&lCultPvPChests &8| &cНе удалось найти сундук с данным ключём"
    help:
      - '&6&lCultPvPChests &8| &fПомощь по командам:'
      - ' &6&l* &fСоздать новый сундук - &e/cultpvpchests create <название сундука> <время обновления> <минимальный онлайн> <задержка>'
      - ' &6&l* &fУстановить локацию сундуку - &e/cultpvpchests set-location <название сундука> &7(Смотрите на блок, который должен быть сундуком)'
      - ' &6&l* &fДобавить новый предмет в сундук - &e/cultpvpchests add-item <название сундука> &7(Держите предмет в руке)'
      - ' &6&l* &fУстановить время открытия сундука - &e/cultpvpchests set-delay <название сундука> <время>'
      - ' &6&l* &fУстановить сообщение сундуку - &e/cultpvpchests set-message <название сундука> <сообщение> &7(Чтобы сделать перенос строки используйте \n)'
      - ' &6&l* &fУстановить минимальный онлайн для открытия - &e/cultpvpchests set-min-online <название сундука> <минимальный онлайн>'
      - ' &6&l* &fУстановить текст голограммы - &e/cultpvpchests set-hologram <название сундука> <сообщение> &7(Чтобы сделать перенос строки используйте \n)'
      - ' &6&l* &fУстановить шанс на появление предмета - &e/cultpvpchests set-item-chance <название сундука> <вероятность>'
    create:
      usage: "&6&lCultPvPChests &8| &fИспользуйте - &e/cultpvpchests create <название сундука> <время обновления> <минимальный онлайн>"
      key-already-exists: "&6&lCultPvPChests &8| &cДанное название уже используется."
      create: "&6&lCultPvPChests &8| &fВы успешно создали новый сундук"
    set-location:
      usage: "&6&lCultPvPChests &8| &fИспользуйте - &e/cultpvpchests set-location <название сундука> &7(Смотрите на блок, который должен быть сундуком)"
      set: "&6&lCultPvPChests &8| &fВы успешно установили локацию сундуку - &a{location}"
    add-item:
      usage: "&6&lCultPvPChests &8| &fИспользуйте - &e/cultpvpchests add-item <название сундука> &7(Держите предмет в руке)"
      material-is-null: "&6&lCultPvPChests &8| &cНе удалось найти предмет в главной руке"
      add: "&6&lCultPvPChests &8| &fВы успешно добавили новый предмет в сундук: &a{item} &fс шансом &e{chance}"
    set-delay:
      usage: "&6&lCultPvPChests &8| &fИспользуйте - &e/cultpvpchests set-delay <название сундука> <время>"
      set: "&6&lCultPvPChests &8| &fВы успешно установили время открытия сундука - &a{time}"
    set-min-online:
      usage: "&6&lCultPvPChests &8| &fИспользуйте - &e/cultpvpchests set-min-online <название сундука> <минимальный онлайн>"
      set: "&6&lCultPvPChests &8| &fВы успешно установили минимальный онлайн &e{online}"
    set-hologram:
      usage: "&6&lCultPvPChests &8| &fИспользуйте - &e/cultpvpchests set-hologram <название сундука> <сообщение> &7(Чтобы сделать перенос строки используйте \n)"
      set: "&6&lCultPvPChests &8| &fВы успешно установили текст для голограммы"
    set-message:
      usage: "&6&lCultPvPChests &8| &fИспользуйте - &e/cultpvpchests set-message <название сундука> <сообщение> &7(Чтобы сделать перенос строки используйте \n)"
      set: "&6&lCultPvPChests &8| &fВы успешно установили сообщение для сундука"

chests: {}