name: CultPvPChests
main: ru.velialcult.pvpchests.CultPvPChests
version: 1.0.1-RELEASE
api-version: 1.16
website: https://leaked-minecraft.pro/velialcult/
softdepend:
  - DecentHolograms
  - HolographicDisplays
  - Multiverse-Core
depend:
  - CultLibrary
commands:
  cultpvpchests: